/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as SolutionsRouteImport } from './routes/solutions'
import { Route as SitemapDotxmlRouteImport } from './routes/sitemap[.]xml'
import { Route as ContactRouteImport } from './routes/contact'
import { Route as AuthRouteImport } from './routes/auth'
import { Route as AboutRouteImport } from './routes/about'
import { Route as AuthenticatedRouteRouteImport } from './routes/_authenticated/route'
import { Route as IndexRouteImport } from './routes/index'
import { Route as SuccessStoriesIndexRouteImport } from './routes/success-stories.index'
import { Route as BlogIndexRouteImport } from './routes/blog.index'
import { Route as SuccessStoriesSlugRouteImport } from './routes/success-stories.$slug'
import { Route as BlogSlugRouteImport } from './routes/blog.$slug'
import { Route as AuthenticatedAdminRouteImport } from './routes/_authenticated/admin'
import { Route as AuthenticatedAdminIndexRouteImport } from './routes/_authenticated/admin.index'
import { Route as AuthenticatedAdminMessagesRouteImport } from './routes/_authenticated/admin.messages'
import { Route as AuthenticatedAdminSuccessStoriesIndexRouteImport } from './routes/_authenticated/admin.success-stories.index'
import { Route as AuthenticatedAdminBlogsIndexRouteImport } from './routes/_authenticated/admin.blogs.index'
import { Route as AuthenticatedAdminSuccessStoriesNewRouteImport } from './routes/_authenticated/admin.success-stories.new'
import { Route as AuthenticatedAdminSuccessStoriesIdRouteImport } from './routes/_authenticated/admin.success-stories.$id'
import { Route as AuthenticatedAdminBlogsNewRouteImport } from './routes/_authenticated/admin.blogs.new'
import { Route as AuthenticatedAdminBlogsIdRouteImport } from './routes/_authenticated/admin.blogs.$id'

const SolutionsRoute = SolutionsRouteImport.update({
  id: '/solutions',
  path: '/solutions',
  getParentRoute: () => rootRouteImport,
} as any)
const SitemapDotxmlRoute = SitemapDotxmlRouteImport.update({
  id: '/sitemap.xml',
  path: '/sitemap.xml',
  getParentRoute: () => rootRouteImport,
} as any)
const ContactRoute = ContactRouteImport.update({
  id: '/contact',
  path: '/contact',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthRoute = AuthRouteImport.update({
  id: '/auth',
  path: '/auth',
  getParentRoute: () => rootRouteImport,
} as any)
const AboutRoute = AboutRouteImport.update({
  id: '/about',
  path: '/about',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedRouteRoute = AuthenticatedRouteRouteImport.update({
  id: '/_authenticated',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const SuccessStoriesIndexRoute = SuccessStoriesIndexRouteImport.update({
  id: '/success-stories/',
  path: '/success-stories/',
  getParentRoute: () => rootRouteImport,
} as any)
const BlogIndexRoute = BlogIndexRouteImport.update({
  id: '/blog/',
  path: '/blog/',
  getParentRoute: () => rootRouteImport,
} as any)
const SuccessStoriesSlugRoute = SuccessStoriesSlugRouteImport.update({
  id: '/success-stories/$slug',
  path: '/success-stories/$slug',
  getParentRoute: () => rootRouteImport,
} as any)
const BlogSlugRoute = BlogSlugRouteImport.update({
  id: '/blog/$slug',
  path: '/blog/$slug',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedAdminRoute = AuthenticatedAdminRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedAdminIndexRoute = AuthenticatedAdminIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AuthenticatedAdminRoute,
} as any)
const AuthenticatedAdminMessagesRoute =
  AuthenticatedAdminMessagesRouteImport.update({
    id: '/messages',
    path: '/messages',
    getParentRoute: () => AuthenticatedAdminRoute,
  } as any)
const AuthenticatedAdminSuccessStoriesIndexRoute =
  AuthenticatedAdminSuccessStoriesIndexRouteImport.update({
    id: '/success-stories/',
    path: '/success-stories/',
    getParentRoute: () => AuthenticatedAdminRoute,
  } as any)
const AuthenticatedAdminBlogsIndexRoute =
  AuthenticatedAdminBlogsIndexRouteImport.update({
    id: '/blogs/',
    path: '/blogs/',
    getParentRoute: () => AuthenticatedAdminRoute,
  } as any)
const AuthenticatedAdminSuccessStoriesNewRoute =
  AuthenticatedAdminSuccessStoriesNewRouteImport.update({
    id: '/success-stories/new',
    path: '/success-stories/new',
    getParentRoute: () => AuthenticatedAdminRoute,
  } as any)
const AuthenticatedAdminSuccessStoriesIdRoute =
  AuthenticatedAdminSuccessStoriesIdRouteImport.update({
    id: '/success-stories/$id',
    path: '/success-stories/$id',
    getParentRoute: () => AuthenticatedAdminRoute,
  } as any)
const AuthenticatedAdminBlogsNewRoute =
  AuthenticatedAdminBlogsNewRouteImport.update({
    id: '/blogs/new',
    path: '/blogs/new',
    getParentRoute: () => AuthenticatedAdminRoute,
  } as any)
const AuthenticatedAdminBlogsIdRoute =
  AuthenticatedAdminBlogsIdRouteImport.update({
    id: '/blogs/$id',
    path: '/blogs/$id',
    getParentRoute: () => AuthenticatedAdminRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/auth': typeof AuthRoute
  '/contact': typeof ContactRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/solutions': typeof SolutionsRoute
  '/admin': typeof AuthenticatedAdminRouteWithChildren
  '/blog/$slug': typeof BlogSlugRoute
  '/success-stories/$slug': typeof SuccessStoriesSlugRoute
  '/blog/': typeof BlogIndexRoute
  '/success-stories/': typeof SuccessStoriesIndexRoute
  '/admin/messages': typeof AuthenticatedAdminMessagesRoute
  '/admin/': typeof AuthenticatedAdminIndexRoute
  '/admin/blogs/$id': typeof AuthenticatedAdminBlogsIdRoute
  '/admin/blogs/new': typeof AuthenticatedAdminBlogsNewRoute
  '/admin/success-stories/$id': typeof AuthenticatedAdminSuccessStoriesIdRoute
  '/admin/success-stories/new': typeof AuthenticatedAdminSuccessStoriesNewRoute
  '/admin/blogs/': typeof AuthenticatedAdminBlogsIndexRoute
  '/admin/success-stories/': typeof AuthenticatedAdminSuccessStoriesIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/auth': typeof AuthRoute
  '/contact': typeof ContactRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/solutions': typeof SolutionsRoute
  '/blog/$slug': typeof BlogSlugRoute
  '/success-stories/$slug': typeof SuccessStoriesSlugRoute
  '/blog': typeof BlogIndexRoute
  '/success-stories': typeof SuccessStoriesIndexRoute
  '/admin/messages': typeof AuthenticatedAdminMessagesRoute
  '/admin': typeof AuthenticatedAdminIndexRoute
  '/admin/blogs/$id': typeof AuthenticatedAdminBlogsIdRoute
  '/admin/blogs/new': typeof AuthenticatedAdminBlogsNewRoute
  '/admin/success-stories/$id': typeof AuthenticatedAdminSuccessStoriesIdRoute
  '/admin/success-stories/new': typeof AuthenticatedAdminSuccessStoriesNewRoute
  '/admin/blogs': typeof AuthenticatedAdminBlogsIndexRoute
  '/admin/success-stories': typeof AuthenticatedAdminSuccessStoriesIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_authenticated': typeof AuthenticatedRouteRouteWithChildren
  '/about': typeof AboutRoute
  '/auth': typeof AuthRoute
  '/contact': typeof ContactRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/solutions': typeof SolutionsRoute
  '/_authenticated/admin': typeof AuthenticatedAdminRouteWithChildren
  '/blog/$slug': typeof BlogSlugRoute
  '/success-stories/$slug': typeof SuccessStoriesSlugRoute
  '/blog/': typeof BlogIndexRoute
  '/success-stories/': typeof SuccessStoriesIndexRoute
  '/_authenticated/admin/messages': typeof AuthenticatedAdminMessagesRoute
  '/_authenticated/admin/': typeof AuthenticatedAdminIndexRoute
  '/_authenticated/admin/blogs/$id': typeof AuthenticatedAdminBlogsIdRoute
  '/_authenticated/admin/blogs/new': typeof AuthenticatedAdminBlogsNewRoute
  '/_authenticated/admin/success-stories/$id': typeof AuthenticatedAdminSuccessStoriesIdRoute
  '/_authenticated/admin/success-stories/new': typeof AuthenticatedAdminSuccessStoriesNewRoute
  '/_authenticated/admin/blogs/': typeof AuthenticatedAdminBlogsIndexRoute
  '/_authenticated/admin/success-stories/': typeof AuthenticatedAdminSuccessStoriesIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/about'
    | '/auth'
    | '/contact'
    | '/sitemap.xml'
    | '/solutions'
    | '/admin'
    | '/blog/$slug'
    | '/success-stories/$slug'
    | '/blog/'
    | '/success-stories/'
    | '/admin/messages'
    | '/admin/'
    | '/admin/blogs/$id'
    | '/admin/blogs/new'
    | '/admin/success-stories/$id'
    | '/admin/success-stories/new'
    | '/admin/blogs/'
    | '/admin/success-stories/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/about'
    | '/auth'
    | '/contact'
    | '/sitemap.xml'
    | '/solutions'
    | '/blog/$slug'
    | '/success-stories/$slug'
    | '/blog'
    | '/success-stories'
    | '/admin/messages'
    | '/admin'
    | '/admin/blogs/$id'
    | '/admin/blogs/new'
    | '/admin/success-stories/$id'
    | '/admin/success-stories/new'
    | '/admin/blogs'
    | '/admin/success-stories'
  id:
    | '__root__'
    | '/'
    | '/_authenticated'
    | '/about'
    | '/auth'
    | '/contact'
    | '/sitemap.xml'
    | '/solutions'
    | '/_authenticated/admin'
    | '/blog/$slug'
    | '/success-stories/$slug'
    | '/blog/'
    | '/success-stories/'
    | '/_authenticated/admin/messages'
    | '/_authenticated/admin/'
    | '/_authenticated/admin/blogs/$id'
    | '/_authenticated/admin/blogs/new'
    | '/_authenticated/admin/success-stories/$id'
    | '/_authenticated/admin/success-stories/new'
    | '/_authenticated/admin/blogs/'
    | '/_authenticated/admin/success-stories/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuthenticatedRouteRoute: typeof AuthenticatedRouteRouteWithChildren
  AboutRoute: typeof AboutRoute
  AuthRoute: typeof AuthRoute
  ContactRoute: typeof ContactRoute
  SitemapDotxmlRoute: typeof SitemapDotxmlRoute
  SolutionsRoute: typeof SolutionsRoute
  BlogSlugRoute: typeof BlogSlugRoute
  SuccessStoriesSlugRoute: typeof SuccessStoriesSlugRoute
  BlogIndexRoute: typeof BlogIndexRoute
  SuccessStoriesIndexRoute: typeof SuccessStoriesIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/solutions': {
      id: '/solutions'
      path: '/solutions'
      fullPath: '/solutions'
      preLoaderRoute: typeof SolutionsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/sitemap.xml': {
      id: '/sitemap.xml'
      path: '/sitemap.xml'
      fullPath: '/sitemap.xml'
      preLoaderRoute: typeof SitemapDotxmlRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/contact': {
      id: '/contact'
      path: '/contact'
      fullPath: '/contact'
      preLoaderRoute: typeof ContactRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth': {
      id: '/auth'
      path: '/auth'
      fullPath: '/auth'
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/about': {
      id: '/about'
      path: '/about'
      fullPath: '/about'
      preLoaderRoute: typeof AboutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated': {
      id: '/_authenticated'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/success-stories/': {
      id: '/success-stories/'
      path: '/success-stories'
      fullPath: '/success-stories/'
      preLoaderRoute: typeof SuccessStoriesIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/blog/': {
      id: '/blog/'
      path: '/blog'
      fullPath: '/blog/'
      preLoaderRoute: typeof BlogIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/success-stories/$slug': {
      id: '/success-stories/$slug'
      path: '/success-stories/$slug'
      fullPath: '/success-stories/$slug'
      preLoaderRoute: typeof SuccessStoriesSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/blog/$slug': {
      id: '/blog/$slug'
      path: '/blog/$slug'
      fullPath: '/blog/$slug'
      preLoaderRoute: typeof BlogSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/admin': {
      id: '/_authenticated/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AuthenticatedAdminRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/admin/': {
      id: '/_authenticated/admin/'
      path: '/'
      fullPath: '/admin/'
      preLoaderRoute: typeof AuthenticatedAdminIndexRouteImport
      parentRoute: typeof AuthenticatedAdminRoute
    }
    '/_authenticated/admin/messages': {
      id: '/_authenticated/admin/messages'
      path: '/messages'
      fullPath: '/admin/messages'
      preLoaderRoute: typeof AuthenticatedAdminMessagesRouteImport
      parentRoute: typeof AuthenticatedAdminRoute
    }
    '/_authenticated/admin/success-stories/': {
      id: '/_authenticated/admin/success-stories/'
      path: '/success-stories'
      fullPath: '/admin/success-stories/'
      preLoaderRoute: typeof AuthenticatedAdminSuccessStoriesIndexRouteImport
      parentRoute: typeof AuthenticatedAdminRoute
    }
    '/_authenticated/admin/blogs/': {
      id: '/_authenticated/admin/blogs/'
      path: '/blogs'
      fullPath: '/admin/blogs/'
      preLoaderRoute: typeof AuthenticatedAdminBlogsIndexRouteImport
      parentRoute: typeof AuthenticatedAdminRoute
    }
    '/_authenticated/admin/success-stories/new': {
      id: '/_authenticated/admin/success-stories/new'
      path: '/success-stories/new'
      fullPath: '/admin/success-stories/new'
      preLoaderRoute: typeof AuthenticatedAdminSuccessStoriesNewRouteImport
      parentRoute: typeof AuthenticatedAdminRoute
    }
    '/_authenticated/admin/success-stories/$id': {
      id: '/_authenticated/admin/success-stories/$id'
      path: '/success-stories/$id'
      fullPath: '/admin/success-stories/$id'
      preLoaderRoute: typeof AuthenticatedAdminSuccessStoriesIdRouteImport
      parentRoute: typeof AuthenticatedAdminRoute
    }
    '/_authenticated/admin/blogs/new': {
      id: '/_authenticated/admin/blogs/new'
      path: '/blogs/new'
      fullPath: '/admin/blogs/new'
      preLoaderRoute: typeof AuthenticatedAdminBlogsNewRouteImport
      parentRoute: typeof AuthenticatedAdminRoute
    }
    '/_authenticated/admin/blogs/$id': {
      id: '/_authenticated/admin/blogs/$id'
      path: '/blogs/$id'
      fullPath: '/admin/blogs/$id'
      preLoaderRoute: typeof AuthenticatedAdminBlogsIdRouteImport
      parentRoute: typeof AuthenticatedAdminRoute
    }
  }
}

interface AuthenticatedAdminRouteChildren {
  AuthenticatedAdminMessagesRoute: typeof AuthenticatedAdminMessagesRoute
  AuthenticatedAdminIndexRoute: typeof AuthenticatedAdminIndexRoute
  AuthenticatedAdminBlogsIdRoute: typeof AuthenticatedAdminBlogsIdRoute
  AuthenticatedAdminBlogsNewRoute: typeof AuthenticatedAdminBlogsNewRoute
  AuthenticatedAdminSuccessStoriesIdRoute: typeof AuthenticatedAdminSuccessStoriesIdRoute
  AuthenticatedAdminSuccessStoriesNewRoute: typeof AuthenticatedAdminSuccessStoriesNewRoute
  AuthenticatedAdminBlogsIndexRoute: typeof AuthenticatedAdminBlogsIndexRoute
  AuthenticatedAdminSuccessStoriesIndexRoute: typeof AuthenticatedAdminSuccessStoriesIndexRoute
}

const AuthenticatedAdminRouteChildren: AuthenticatedAdminRouteChildren = {
  AuthenticatedAdminMessagesRoute: AuthenticatedAdminMessagesRoute,
  AuthenticatedAdminIndexRoute: AuthenticatedAdminIndexRoute,
  AuthenticatedAdminBlogsIdRoute: AuthenticatedAdminBlogsIdRoute,
  AuthenticatedAdminBlogsNewRoute: AuthenticatedAdminBlogsNewRoute,
  AuthenticatedAdminSuccessStoriesIdRoute:
    AuthenticatedAdminSuccessStoriesIdRoute,
  AuthenticatedAdminSuccessStoriesNewRoute:
    AuthenticatedAdminSuccessStoriesNewRoute,
  AuthenticatedAdminBlogsIndexRoute: AuthenticatedAdminBlogsIndexRoute,
  AuthenticatedAdminSuccessStoriesIndexRoute:
    AuthenticatedAdminSuccessStoriesIndexRoute,
}

const AuthenticatedAdminRouteWithChildren =
  AuthenticatedAdminRoute._addFileChildren(AuthenticatedAdminRouteChildren)

interface AuthenticatedRouteRouteChildren {
  AuthenticatedAdminRoute: typeof AuthenticatedAdminRouteWithChildren
}

const AuthenticatedRouteRouteChildren: AuthenticatedRouteRouteChildren = {
  AuthenticatedAdminRoute: AuthenticatedAdminRouteWithChildren,
}

const AuthenticatedRouteRouteWithChildren =
  AuthenticatedRouteRoute._addFileChildren(AuthenticatedRouteRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuthenticatedRouteRoute: AuthenticatedRouteRouteWithChildren,
  AboutRoute: AboutRoute,
  AuthRoute: AuthRoute,
  ContactRoute: ContactRoute,
  SitemapDotxmlRoute: SitemapDotxmlRoute,
  SolutionsRoute: SolutionsRoute,
  BlogSlugRoute: BlogSlugRoute,
  SuccessStoriesSlugRoute: SuccessStoriesSlugRoute,
  BlogIndexRoute: BlogIndexRoute,
  SuccessStoriesIndexRoute: SuccessStoriesIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
